server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ikuzo
    username: ikuzo
    password: ikuzo1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always   # 최초 테이블 생성용 ! 생성 후에는 never로 바꿔주세요 !!