server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ikuzo
    username: ikuzo
    password: ikuzo1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  batch:
    initialize-schema: ALWAYS   # 최초 테이블 생성용
weather:
  batch:
    cron: "0 0/30 * * * *"
logging:
  level:
    # Spring Cache 관련 디버그 로그 활성화 (캐시 Hit/Miss 추적)
    org.springframework.cache: DEBUG
    org.springframework.cache.interceptor: TRACE