server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ikuzo
    username: ikuzo
    password: ikuzo1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update