spring:
  profiles:
    active:
      - local
  jackson:
    time-zone: Asia/Seoul
  batch:
    job:
      enabled: false      # 부팅 시 배치 자동 실행 방지

external:
  kma:
    base-url: "https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0"
    service-key: "${KMA_SERVICE_KEY_ENC}"
    timeout-ms: 5000
  kakao:
    base-url: "https://dapi.kakao.com"
    rest-api-key: "${API_KAKAO_KEY}"

weather:
  batch:
    enabled: true
    cron: "0 0/30 * * * *"