spring:
  profiles:
    active:
      - local

otboo:
  jwt:
    access-token:
      secret: ${JWT_ACCESS_SECRET}
      expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:3600000} # 60 minutes
sse:
  timeout: 300_000
  event-queue-capacity: 100