server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.ikuzo.otboo: INFO
    org.springframework.web: WARN
    org.hibernate: WARN