name: Deploy to AWS ECS(CD)

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-northeast-2

  # Public ECR (us-east-1 고정)
  ECR_PUBLIC_REGION: us-east-1
  ECR_APP_REPO_URI: public.ecr.aws/j5n8s8m1/ikuzo
  ECR_NGINX_REPO_URI: public.ecr.aws/j5n8s8m1/ikuzo-nginx

  # ECS
  ECS_CLUSTER: ikuzo
  ECS_SERVICE: ikuzo-service

jobs:
  docker:
    name: Build and Push Docker Images (app + nginx)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Configure AWS credentials for Public ECR
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_KEY }}
          aws-region: ${{ env.ECR_PUBLIC_REGION }}

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region $ECR_PUBLIC_REGION \
            | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build Spring Boot jar
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar

      - name: Build, tag and push APP image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_APP_REPO_URI:latest -t $ECR_APP_REPO_URI:$IMAGE_TAG .
          docker push $ECR_APP_REPO_URI:latest
          docker push $ECR_APP_REPO_URI:$IMAGE_TAG

      # nginx Dockerfile 위치가 repo 루트/nginx/ 라고 가정. 경로 다르면 수정
      - name: Build, tag and push NGINX image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f nginx/Dockerfile -t $ECR_NGINX_REPO_URI:latest -t $ECR_NGINX_REPO_URI:$IMAGE_TAG nginx
          docker push $ECR_NGINX_REPO_URI:latest
          docker push $ECR_NGINX_REPO_URI:$IMAGE_TAG

  deploy:
    name: Deploy to ECS
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials for ECS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 태스크 정의 파일을 로컬에서 읽어서, 두 컨테이너(app, nginx)의 image를 sha 태그로 치환
      - name: Prepare final task definition (set both app/nginx images)
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          APP_IMG="$ECR_APP_REPO_URI:$IMAGE_TAG"
          NGINX_IMG="$ECR_NGINX_REPO_URI:$IMAGE_TAG"

          jq --arg app "$APP_IMG" --arg ngx "$NGINX_IMG" '
            del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy
            )
            | .containerDefinitions = (
                .containerDefinitions
                | map(
                    if .name == "app" then .image = $app
                    elif .name == "nginx" then .image = $ngx
                    else .
                    end
                  )
              )
          ' task-definition.json > final-task-def.json

      - name: Register new task definition
        id: register-task
        run: |
          arn=$(aws ecs register-task-definition \
            --cli-input-json file://final-task-def.json \
            --query "taskDefinition.taskDefinitionArn" --output text)
          echo "task_def_arn=$arn" >> $GITHUB_OUTPUT

      - name: Stop existing ECS service temporarily
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --desired-count 0
          aws ecs wait services-stable \
            --cluster $ECS_CLUSTER \
            --services $ECS_SERVICE

      - name: Deploy new task definition to ECS service
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --task-definition ${{ steps.register-task.outputs.task_def_arn }} \
            --desired-count 1
          aws ecs wait services-stable \
            --cluster $ECS_CLUSTER \
            --services $ECS_SERVICE

      - name: Deployment success
        if: success()
        run: |
          echo "::notice::✅ Deployed!"
          echo "Task Definition: ${{ steps.register-task.outputs.task_def_arn }}"

      - name: Deployment failed
        if: failure()
        run: |
          echo "::error::❌ Deployment failed. Check ECS events & CloudWatch logs."

      # latest 외 태그 정리
      - name: Clean up old ECR Public images (keep only 'latest')
        if: success()
        env:
          REPO_APP: ${{ env.ECR_APP_REPO_URI }}
          REPO_NGX: ${{ env.ECR_NGINX_REPO_URI }}
          REGION: ${{ env.ECR_PUBLIC_REGION }}
        run: |
          clean_repo () {
            local REPO=$1
            local REGION=$2
            local REPO_NAME=$(echo $REPO | awk -F'/' '{print $NF}')

            LATEST_DIGEST=$(aws ecr-public describe-images --region $REGION \
              --repository-name $REPO_NAME \
              --query 'imageDetails[?imageTags != null && contains(imageTags, `latest`)].[imageDigest]' \
              --output text | head -n 1)

            [ -z "$LATEST_DIGEST" ] && return 0

            ALL=$(aws ecr-public describe-images --region $REGION \
              --repository-name $REPO_NAME \
              --query 'imageDetails[*].[imageDigest,imageTags[]]' --output json)

            TO_DELETE=$(echo "$ALL" | jq -r --arg L "$LATEST_DIGEST" \
              '[.[] | select(.[0] != $L) | .[0]] | unique | .[]')

            if [ -n "$TO_DELETE" ]; then
              echo "$TO_DELETE" | xargs -I {} aws ecr-public batch-delete-image \
                --region $REGION --repository-name $REPO_NAME \
                --image-ids imageDigest={}
            fi
          }

          clean_repo "$REPO_APP" "$REGION"
          clean_repo "$REPO_NGX" "$REGION"
